services:
  - type: web
    name: car4-ltc
    env: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /
    plan: starter
    autoDeploy: true
    buildCommand: ""
    startCommand: python app.py

  # 定時任務 (Cron Jobs)
  - type: cron
    name: car4-reservation-cron
    env: docker
    dockerfilePath: ./Dockerfile.render
    schedule: "1 16 * * 0,3"  # 台灣週一和週四 00:01 (UTC 週日和週三 16:01)
    startCommand: python cron_job.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1

  - type: cron
    name: car4-dispatch-cron
    env: docker
    dockerfilePath: ./Dockerfile.render
    schedule: "10 16 * * 0,3"  # 台灣週一和週四 00:10 (UTC 週日和週三 16:10)
    startCommand: python cron_dispatch.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1 