[project]
name = "car4-chromium"

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python3 app.py"
healthCheckPath = "/"
healthCheckTimeout = 300

[env]
PORT = "8080" 

[cron]
# 每週一和週四台灣時間 00:01 執行預約
# Zeabur 使用 UTC 時間，台灣時間 UTC+8
# 台灣週一 00:01 = 週日 16:01 UTC
# 台灣週四 00:01 = 週三 16:01 UTC
"1 16 * * 0,3" = "python3 cron_job.py"

# 每週一和週四台灣時間 00:10 執行派車結果查詢
# 台灣週一 00:10 = 週日 16:10 UTC
# 台灣週四 00:10 = 週三 16:10 UTC
"10 16 * * 0,3" = "python3 cron_dispatch.py"